import { expect, test } from '@playwright/test'

test('purchase price opens a complete share breakdown on touch', async ({ page }) => {
  await page.goto('/money')
  await page.getByRole('button', { name: /View breakdown for/ }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Who owes what' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Who paid', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('night palette persists without changing the mobile day count', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('howsehowld:theme', 'light'))
  await page.goto('/')
  await expect(page.getByRole('group', { name: 'Visible dates' }).getByRole('button')).toHaveCount(3)
  await page.getByRole('button', { name: 'Use dark mode' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('link', { name: /Money/ }).last().click()
  await expect(page.getByRole('button', { name: 'Use light mode' })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('howsehowld:theme'))).toBe('dark')
})

test('owner adds a garage tile and parks a car using touch controls', async ({ page }) => {
  await page.goto('/driveway')
  await page.getByRole('button', { name: 'Add slot', exact: true }).click()
  await page.getByRole('button', { name: 'Properties for slot 4: empty' }).click()
  await page.getByRole('combobox', { name: 'Slot type' }).selectOption('garage')
  await page.getByRole('spinbutton', { name: 'Width (cells)', exact: true }).fill('2')
  await page.getByRole('dialog').getByRole('button', { name: 'Done', exact: true }).click()
  await page.getByRole('button', { name: 'Save driveway', exact: true }).click()
  await expect(page.locator('[data-slot-width="2"]')).toContainText('Garage')
  await page.getByRole('button', { name: 'Park in slot 4: empty' }).click()
  await page.getByRole('combobox', { name: 'Vehicle', exact: true }).selectOption('vehicle-brandon')
  await expect(page.getByRole('button', { name: 'Park in slot 4: Red Mazda' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Park in slot 3: empty' })).toBeAttached()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('correcting a purchase updates every share and the displayed total', async ({ page }) => {
  await page.goto('/money')
  await page.getByRole('button', { name: 'View breakdown for Toilet paper & paper towel' }).click()
  await page.getByRole('button', { name: 'Edit price' }).click()
  await page.getByRole('textbox', { name: 'Correct purchase total' }).fill('40.04')
  await page.getByRole('button', { name: 'Save total' }).click()
  await expect(page.getByRole('dialog').getByText('$40.04', { exact: true })).toHaveCount(2)
  await expect(page.getByRole('dialog').getByText('$40.04', { exact: true }).first()).toBeVisible()
  await expect(page.getByRole('dialog').getByText('$10.01', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  await expect(page.getByRole('button', { name: 'View breakdown for Toilet paper & paper towel' })).toContainText('$40.04')
})

test('desktop hover shows shares and both palettes render', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/money')
  await page.getByRole('button', { name: 'View breakdown for Toilet paper & paper towel' }).getByText('$48.36', { exact: true }).hover()
  await expect(page.getByRole('tooltip')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('money-hover.png') })
  await page.getByRole('button', { name: 'View breakdown for Toilet paper & paper towel' }).click()
  await page.screenshot({ path: testInfo.outputPath('purchase-detail.png') })
  await page.getByRole('button', { name: 'Close', exact: true }).click()
  const toggle = page.getByRole('button', { name: 'Use dark mode' })
  if (await toggle.isVisible()) await toggle.click()
  await page.screenshot({ path: testInfo.outputPath('money-dark.png') })
})
